# Generated by Django 3.2.4 on 2021-07-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('city_coords', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Equipment_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=20, verbose_name='Тип оборудования')),
                ('equipment_model', models.CharField(max_length=100, verbose_name='Модель оборудования')),
                ('equipment_cost', models.FloatField()),
            ],
            options={
                'verbose_name': 'Модель оборудования',
                'verbose_name_plural': 'Модели оборудования',
            },
        ),
        migrations.CreateModel(
            name='Equipment_spots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=100, verbose_name='Оборудование')),
                ('nearest_city', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Станция с оборудованием',
                'verbose_name_plural': 'Станции с оборудованием',
            },
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'Погода', 'verbose_name_plural': 'Погода'},
        ),
    ]
